Initial commits
Initial commits

Fixed UnitStripWarnings

Was making unnecessarily doing np.array(<Quantity>)

Remove pandas_array import from __init__.py

This should mean that all the tests pass again.

Given pint's focus on avoiding dependencies, we shouldn't import the pandas interface by default (as it depends on pandas). If users want it, they'll have to do `from pint.pandas_array import QuantityArray` which is a little longer than `from pint import QuantityArray` but I think that's ok as it's a specialised usage.

Check array size dimensions when performing arithermetic/compartive operations

Add check to ensure array sizes of RHS and LHS match
Prevented typeerrors when performing operation with a single value
quantity

Fix dimensionality error message

Fixes great DimensionalityError that occurs when you pow with a single
value quantity.
DimensionalityError: Cannot convert from 'dimensionless' to
'dimensionless'

Add docs

Add documentation

Add DF accessors, remove docs

Removing docs as I haven't worked out how to set them up properly to
past tests.
DF accessors added to ease going between QAs and numerical arrays.

More accessors

More accessors

Initial hacks to look at adding pandas interface

Getting somewhere, no more errors...

Pass 2 more tests

Get all the pandas tests I can going

Before trying to remove data thing

Something seems to be working e.g.

>>> from pint.pandas_interface import PintArray
>>> import pandas as pd

>>> df = pd.DataFrame({"address": PintArray([1, 2, 3])})
>>> df
          address
0 1 dimensionless
1 2 dimensionless
2 3 dimensionless

>>> df.dtypes
address    Pint
dtype: object

>>> df['address']
0   1 dimensionless
1   2 dimensionless
2   3 dimensionless
Name: address, dtype: Pint

>>> df['address'].values.data
<Quantity([1 2 3], 'dimensionless')>

but unfortunately

>>> df['address'].values
<pint.pandas_interface.PintArray object at 0x117517f28>

Write down my env setup

A minor improvement

Start again, basically

Clean up, ready to start building

42 tests passed, that is a start

Add some more thoughts about how to do this sensibly

52 passed

More passing than failing, that is something. arithmetic ops next looks painful

Pass a few more tests

Over 100 tests passed, seems to be going ok...

Only missing and setitem to go

Pass all the pandas interface tests

All the stuff I needed to work out why PintArray.values looked weird

Fiddling around more with how things should work

Add a few more thoughts

Add two failing tests that should really pass

Add tiny comment to see if CI will run

Step 1 of attempt to get CI going

Add arithmetic and comparison ops , DF acccessors

arithmetic and comparison ops from my QuantityArrays
DF accessors to get the documentation nb working

Get TestUserInterface tests working

Added mismatching dimensions check

Step 2 of attempt to get CI going

Step 3 of attempt to get CI going

Step 4 of attempt to get CI going

Step 5 of attempt to get CI going (bit more happening now)

Make README point at my fork, this will be temporary

failing Attempts to get reverse ops working

Add PintArray.fillna, fixes test_fillna_scalar

Revert "Add PintArray.fillna, fixes test_fillna_scalar"

This reverts commit ef910f3840ac9c00e0838fe1c89a541d3ace74c9.

back to merge point

Remove __iter__ from scalar Quantity

To prevent pandas' is_list_like recognising scalar quanties as
non-scalars.

Add dtype, copy kwargs to PA.__array__

Turn off arithmetic and compartive ops to see test results

added ops back, dimensionalityError childs from TypeError

Made dimensionalityError a child of TypeError to allow to pass
pandas'TestArithmeticOps()

Added methods to arith tests that excpect results instead TypeErrors

Switched the pandas build to top of queue so it fails faster

Add check to some arithemetics so Q*PA or Q*s return NotImplemented

NotImplimented attempt 2

series + array is an odd one

less tests failing

started on comparisons

some error tests

divmod wasnt too hard :o

the last test?

Series accessors

Tidy up tests

Tweak based on andrew comments

Remove unitstrips from isna()

remove unitstrip warnining for ops

fix value_counts and it's test

revert the na_Cmp

revert binop warning check

SetItem warning debugging

Testmethods

fixes TestGetItem hitting unitstrips when comparing nans

change to __array__ seems to work

pint_eval uses DefinitionSyntaxError in place of general Exception

This allows clients to catch pint-specific errors, rather than a blanket
`catch Exception`.

Partial progress towards #374

Add example and tidy up source a tiny bit

get __array__ working as expected

Tidy up

forgot to save a file

Get tests passing again

Change to using pandas master branch

Series accessor test

series accessor fix

last of the series accessor tests

Fix dimensionality error message

Fixes great DimensionalityError that occurs when you pow with a single
value quantity.
DimensionalityError: Cannot convert from 'dimensionless' to
'dimensionless'

Add docs

Add documentation

Add DF accessors, remove docs

Removing docs as I haven't worked out how to set them up properly to
past tests.
DF accessors added to ease going between QAs and numerical arrays.

More accessors

More accessors

Initial hacks to look at adding pandas interface

Getting somewhere, no more errors...

Pass 2 more tests

Get all the pandas tests I can going

Before trying to remove data thing

Something seems to be working e.g.

>>> from pint.pandas_interface import PintArray
>>> import pandas as pd

>>> df = pd.DataFrame({"address": PintArray([1, 2, 3])})
>>> df
          address
0 1 dimensionless
1 2 dimensionless
2 3 dimensionless

>>> df.dtypes
address    Pint
dtype: object

>>> df['address']
0   1 dimensionless
1   2 dimensionless
2   3 dimensionless
Name: address, dtype: Pint

>>> df['address'].values.data
<Quantity([1 2 3], 'dimensionless')>

but unfortunately

>>> df['address'].values
<pint.pandas_interface.PintArray object at 0x117517f28>

Write down my env setup

A minor improvement

Start again, basically

Clean up, ready to start building

42 tests passed, that is a start

Add some more thoughts about how to do this sensibly

52 passed

More passing than failing, that is something. arithmetic ops next looks painful

Pass a few more tests

Over 100 tests passed, seems to be going ok...

Only missing and setitem to go

Pass all the pandas interface tests

All the stuff I needed to work out why PintArray.values looked weird

Fiddling around more with how things should work

Add a few more thoughts

Add two failing tests that should really pass

Add tiny comment to see if CI will run

Step 1 of attempt to get CI going

Add arithmetic and comparison ops , DF acccessors

arithmetic and comparison ops from my QuantityArrays
DF accessors to get the documentation nb working

Get TestUserInterface tests working

Added mismatching dimensions check

Step 2 of attempt to get CI going

Step 3 of attempt to get CI going

Step 4 of attempt to get CI going

Step 5 of attempt to get CI going (bit more happening now)

Make README point at my fork, this will be temporary

failing Attempts to get reverse ops working

Add PintArray.fillna, fixes test_fillna_scalar

Revert "Add PintArray.fillna, fixes test_fillna_scalar"

This reverts commit ef910f3840ac9c00e0838fe1c89a541d3ace74c9.

Add PintArray.fillna, fixes test_fillna_scalar

Revert "Add PintArray.fillna, fixes test_fillna_scalar"

This reverts commit ef910f3840ac9c00e0838fe1c89a541d3ace74c9.

back to merge point

Remove __iter__ from scalar Quantity

To prevent pandas' is_list_like recognising scalar quanties as
non-scalars.

Add dtype, copy kwargs to PA.__array__

Turn off arithmetic and compartive ops to see test results

added ops back, dimensionalityError childs from TypeError

Made dimensionalityError a child of TypeError to allow to pass
pandas'TestArithmeticOps()

Added methods to arith tests that excpect results instead TypeErrors

Switched the pandas build to top of queue so it fails faster

Add check to some arithemetics so Q*PA or Q*s return NotImplemented

NotImplimented attempt 2

series + array is an odd one

less tests failing

started on comparisons

some error tests

divmod wasnt too hard :o

the last test?

Series accessors

Tidy up tests

series + array is an odd one

less tests failing

started on comparisons

some error tests

divmod wasnt too hard :o

the last test?

Series accessors

Tidy up tests

Tweak based on andrew comments

Add example and tidy up source a tiny bit

Remove checkpoints from repo

Remove unitstrips from isna()

remove unitstrip warnining for ops

fix value_counts and it's test

revert the na_Cmp

revert binop warning check

SetItem warning debugging

Testmethods

fixes TestGetItem hitting unitstrips when comparing nans

change to __array__ seems to work

get __array__ working as expected

Tidy up

forgot to save a file

Get tests passing again

Change to using pandas master branch

Update example notebook for pull request

Put README back for pull request

Fix code coverage test

Tweak again

Add better tests of dataframe stuff

Update example notebook again

Rebase and rerun example

Work out how to do coverage properly

Try to fix coverage again

Update to minimal working environment

Attempt 1 at docs

Put testsuite discovery back to default

Remove spurious extra line in testsuite discovery

Try adding link to pandas documentation in index

Remove example csv

Remove packageresouce reliance

Put test csv back in

Put test csv back in